name: build
on:
  push:
  pull_request:
  schedule:
    - cron: '23 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: 01A Calling Reusable Workflow
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      packages: |
            rmf_fleet_adapter
            rmf_task_ros2
            rmf_traffic_ros2
            rmf_websocket
      colcon-defaults: |
            potato2
            potato3
    secrets: inherit
